#!/bin/bash --login

HOME=/services/medusa
BOOK_TRACKER_HOME=$HOME/book-tracker
export RAILS_ENV=production

# Start Passenger
( cd $BOOK_TRACKER_HOME ; bundle exec passenger start -e production -d -p 8080)

exit 0
