#!/bin/bash --login

source $HOME/bin/env.sh

#Make children have lower io and cpu priority
ionice -c2 -n5 -p $$
renice +4 -p $$

#Start local FITS server
echo "Starting local FITS server"
cd $FITS_SERVER_HOME
./run-queue.sh stop
./run-queue.sh start

exit 0
