#!/bin/bash --login

source $HOME/bin/env.sh

#Make children have lower io and cpu priority
ionice -c2 -n5 -p $$
renice +4 -p $$

#Start Fixity server
echo "Starting fixity server"
cd $FIXITY_SERVER_HOME 
./medusa_fixity.sh stop
./medusa_fixity.sh start

exit 0
