#!/bin/bash --login

HOME=/services/medusa
MEDUSA_HOME=$HOME/medusa
export RAILS_ENV=production

#Stop delayed_job
( cd $MEDUSA_HOME ; bundle exec rake medusa:delayed_job:stop )

# Stop Passenger
( cd $MEDUSA_HOME ; bundle exec passenger stop )

#Stop daemon to pick up incoming messages
#Stop after passenger so cron doesn't respawn
( cd $MEDUSA_HOME ; bundle exec rake daemon:message_receiver:stop )

exit 0