#!/bin/bash --login

HOME=/services/medusa
MEDUSA_HOME=$HOME/medusa
export RAILS_ENV=production

#update information for the bit level file group caches
( cd $MEDUSA_HOME ; bundle exec rake medusa:cache:update_bit_level_metrics )

exit 0
