#!/bin/bash
###
### backup_start - service hook for shutting down  services; called by /etc/???
###

# Load environment variables
HOME=/services/medusa
. $HOME/.bashrc

DATESTAMP=`date "+%Y%m%d"`
BACKUP_DIR=$HOME/pgsql/backup

# Dump the DB to a file
/usr/bin/pg_dumpall > $BACKUP_DIR/pg_dump_${DATESTAMP}.sql
# Remove old backups
find $BACKUP_DIR -mtime +30 -delete

