#!/bin/bash
###
### boot - service hook for booting up services; called by /etc/init.d/services_startup
###

# Load environment variables
HOME=/services/medusa
. $HOME/.bashrc

# Start PostgreSQL
$HOME/bin/start-postgres

# Start RabbitMQ
$HOME/bin/start-rabbitmq

# Start Glacier server
$HOME/bin/start-glacier

# Start Tomcat
$HOME/bin/start-tomcat

# Start Rais
$HOME/bin/start-rails

