#!/bin/bash
###
### boot - service hook for booting up services; called by /etc/init.d/services_startup
###

# Load environment variables
HOME=/services/medusa
. $HOME/.bashrc

# Start PostgreSQL
#$HOME/bin/start-postgres

# Start Glacier server
$HOME/bin/start-glacier

# Start Fixity server
$HOME/bin/start-fixity

# Start Rais
$HOME/bin/start-rails

#start fedora stuff
#$HOME/bin/start-fedora
#$HOME/bin/start-solr
#$HOME/bin/start-fedora-indexing
