#!/bin/bash
###
### shutdown - service hook for shutting down  services; called by /etc/init.d/services_startup
###

# Load environment variables
HOME=/services/medusa
. $HOME/.bashrc

# Stop Rails
$HOME/bin/stop-rails

# Stop Fixity server
$HOME/bin/stop-fixity

# Stop Glacier server
$HOME/bin/stop-glacier

# Stop PostgreSQL
#$HOME/bin/stop-postgres

# Stop fedora stuff
$HOME/bin/stop-fedora-indexing
$HOME/bin/stop-solr
$HOME/bin/stop-fedora

# Stop whatever
