#!/bin/bash
###
### shutdown - service hook for shutting down  services; called by /etc/init.d/services_startup
###

# Load environment variables
. $HOME/.bashrc

# Stop Rails
#$HOME/bin/stop-rails

# Stop fits
#$HOME/bin/stop-fits

# Stop Fixity server
#$HOME/bin/stop-fixity

# Stop Glacier server
#$HOME/bin/stop-glacier

# Stop whatever
