#!/bin/bash
###
### shutdown - service hook for shutting down  services; called by /etc/init.d/services_startup
###

# Load environment variables
HOME=/services/medusa
. $HOME/.bashrc

# Stop Rails
$HOME/bin/stop-rails

# Stop Tomcat
$HOME/bin/stop-tomcat

#Stop RabbitMQ
$HOME/bin/stop-rabbitmq

# Stop PostgreSQL
$HOME/bin/stop-postgres

# Stop whatever
